### ISSUE TITLE
Bicep package inquiry

### ISSUE THREAD

**Issue by ctmcisco** [piraces/chocolatey-packages#1]
Seems this package has no chocolateyinstall.ps1. Just reaching out to see if this is something that is being worked on or if the package was discontinued?

https://community.chocolatey.org/packages/bicep#files

**Comment by piraces** [comment]
Hello @ctmcisco , **yes the package is being worked on and updated regularly**.
In the case of the bicep package, there is no need of a `chocolateyinstall.ps1`.

Which I actually use is an [appveyor CI scheduled process](https://ci.appveyor.com/project/piraces/chocolatey-packages) to check for updates and perform automatic upgrades of my mantained packages with a [powershell script](https://github.com/piraces/chocolatey-packages/blob/main/update_all.ps1) and [AU](https://github.com/majkinetor/au).

The update script downloads the latest `.exe` of bicep and upload it to chocolatey. You can check the SHA512 of the binary in chocolatey or install it and run `bicep -v` to check it is in the latest version.

- You can see the automatic commits [here](https://github.com/piraces/chocolatey-packages/commits/main/automatic/bicep).
- And a list of run reports in [this gist](https://gist.github.com/piraces/934662dc159cbb8aa7dade125b15588f).

Hope this answer your question and provides more info on the process.
Feel free to reopen the issue or contact me if you have another question 😄
